Algoritmo "Exercicio5"
// Autor: Daniel Medeiros da Silva
// Data: 03/08/2026

Var // Declaracao de variaveis
	numero: inteiro

Inicio	// Inicia o programa
	leia(numero) // le o numero digitado pelo usuario
	
  se (numero >= 0) entao // se o numero for maior ou igual a zero:
  	escreva("Positivo") // imprime "Positivo"
  senao // se não
  	escreva("Negativo") // imprime "Negativo"
	fimse // fim da condicional
  
FimAlgoritmo // Finaliza o programa