Algoritmo "Exercicio1"
// Autor: Daniel Medeiros da Silva
// Data: 03/08/2026

Var // declaracao de variaveis
	numero: inteiro
  
Inicio	// inicia o programa
	escreval("Digite um número: ") // solicita um numero do usuario
  leia(numero) // le o numero digitado pelo usuario
  
  // imprime o dobro e o triplo do numero informado
  escreval("O dobro de ",numero," é ",numero * 2," e o seu triplo é ",numero * 3) 
  
FimAlgoritmo // finaliza o programa