Algoritmo "Exercicio2"
// Autor: Daniel Medeiros da Silva
// Data: 03/08/2026

Var // declaracao de variaveis
	numero: inteiro
  
Inicio	// inicia o programa
	escreval("Digite um número: ") // solicita um numero do usuario
  leia(numero) // le o numero digitado pelo usuario
  
  // imprime o sucessor e antecessor do numero informado
  escreval("O sucessor de ",numero," é ",numero + 1," e o seu antecessor é ",numero - 1) 
  
FimAlgoritmo // finaliza o programa