Algoritmo "Exercicio4"
// Autor: Daniel Medeiros da Silva
// Data: 03/08/2026

Var // Declaracao de variaveis
	idade: inteiro

Inicio	// Inicia o programa
	leia(idade) // le o numero digitado pelo usuario
	
  se (idade >= 18) entao// Se a idade for maior ou igual a 18:
  	escreva("Pode dirigir") // Imprime "Pode dirigir"
  senao // Se não
		escreva("Não pode dirigir") // Imprime "Não pode dirigir"
 	fimse // Encerra a condicional
  
FimAlgoritmo // Finaliza o programa