algoritmo "Exercicio4"
// Autor: Daniel Medeiros da Silva
// Data: 06/08/2026

var // declaração de variáveis
  i, numero: inteiro

inicio // inicio do programa

  // solicita um numero do usuario
  escreval("Digite um numero qualquer: ")
  leia(numero)

  // conta de 1 ate o numero do usuario de 2 em 2
  para i de 1 ate numero passo 2 faca
    // imprime o numero na tela
    escreval(i)
  fimpara

fimalgoritmo // fim do programa
